# Generated by Django 4.1.4 on 2023-02-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0007_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'CustomUser', 'verbose_name_plural': 'CustomUsers'},
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('email', 'username', 'first_name')},
        ),
    ]
