# Generated by Django 4.1.4 on 2023-03-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0008_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_profile_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
