# Generated by Django 4.1.4 on 2023-01-28 10:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('collage_name', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=10, null=True)),
                ('user', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('host', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=15)),
            ],
        ),
    ]
