# Generated by Django 4.1.4 on 2023-02-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_database_info_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_info',
            name='db_host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='database_info',
            name='db_password',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='database_info',
            name='db_port',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='database_info',
            name='db_user',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
