# Generated by Django 4.1.4 on 2023-02-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_database_info_db_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_info',
            name='db_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
