# Generated by Django 4.1.4 on 2023-02-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_database_info_db_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_info',
            name='college_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='database_info',
            name='db_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
