# Generated by Django 4.1.4 on 2023-02-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_database_info_college_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='database_info',
            unique_together={('db_name', 'db_user'), ('college_name', 'db_name')},
        ),
    ]
