# Generated by Django 4.1.4 on 2022-12-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('PublicId', models.CharField(max_length=100, null=True, unique=True)),
                ('FirstName', models.CharField(max_length=100, null=True)),
                ('LastName', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Country', models.CharField(max_length=20, null=True)),
                ('Field', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('SkillName', models.CharField(max_length=80)),
                ('PublicId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UrlSearch.basicinformation')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeDetails',
            fields=[
                ('id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('CollegeName', models.CharField(max_length=100)),
                ('DegreeName', models.CharField(max_length=100)),
                ('StartYear', models.IntegerField()),
                ('EndYear', models.IntegerField()),
                ('PublicId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UrlSearch.basicinformation')),
            ],
        ),
    ]
