# Generated by Django 4.1.4 on 2022-12-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collegedetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skills',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
