# Generated by Django 4.1.4 on 2022-12-20 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UrlSearch', '0002_alter_basicinformation_id_alter_collegedetails_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedetails',
            name='PublicId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UrlSearch.basicinformation'),
            preserve_default=False,
        ),
    ]
