# Generated by Django 4.1.4 on 2022-12-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlSearch', '0005_alter_collegedetails_endyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedetails',
            name='EndYear',
            field=models.CharField(max_length=15),
        ),
    ]
