# Generated by Django 4.1.4 on 2023-03-01 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_designation_list_college_designation_list'),
        ('UrlSearch', '0006_alter_collegedetails_endyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='batch_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='college_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_department', to='departments.department'),
        ),
    ]
