# Generated by Django 4.1.4 on 2023-03-01 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_designation_list_college_designation_list'),
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('UrlSearch', '0007_basicinformation_batch_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyperiodicTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
                ('batch_year', models.CharField(max_length=4, null=True)),
                ('college_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_college', to='departments.college')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_department', to='departments.department')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
