# Generated by Django 4.1.4 on 2023-03-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrlSearch', '0008_myperiodictask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyperiodicTask',
        ),
    ]
