# Generated by Django 4.1.4 on 2023-03-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_designation_list_college_designation_list'),
        ('UrlSearch', '0009_delete_myperiodictask'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyperiodicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, null=True, unique=True)),
                ('days', models.IntegerField(max_length=1000, null=True)),
                ('batch_year', models.CharField(max_length=4, null=True)),
                ('college_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_college', to='departments.college')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_department', to='departments.department')),
            ],
        ),
    ]
