# Generated by Django 4.1.4 on 2023-03-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlSearch', '0010_myperiodictask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myperiodictask',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
