# Generated by Django 4.1.4 on 2023-03-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlSearch', '0011_alter_myperiodictask_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformation',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
