# Generated by Django 4.1.4 on 2023-03-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlSearch', '0012_alter_basicinformation_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
