# Generated by Django 4.1.4 on 2023-03-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('departments', '0002_rename_designation_list_college_designation_list'),
        ('UrlSearch', '0013_basicinformation_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
                ('task_name', models.CharField(max_length=100, null=True, unique=True)),
                ('days', models.IntegerField(null=True)),
                ('batch_year', models.CharField(max_length=4, null=True)),
                ('college_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_college', to='departments.college')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_department', to='departments.department')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
        migrations.DeleteModel(
            name='MyperiodicTask',
        ),
    ]
