# Generated by Django 4.1.4 on 2023-03-02 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0002_rename_designation_list_college_designation_list'),
        ('UrlSearch', '0014_periodictask_delete_myperiodictask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('batch_year', models.CharField(max_length=4, null=True)),
                ('college_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.college')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_task', to='django_celery_results.taskresult')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
