# Generated by Django 4.1.4 on 2023-03-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlSearch', '0015_tasksinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksinfo',
            name='task',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
