# Generated by Django 4.1.4 on 2023-03-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlSearch', '0016_alter_tasksinfo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksinfo',
            name='department',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
