# Generated by Django 4.1.4 on 2023-03-02 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_designation_list_college_designation_list'),
        ('UrlSearch', '0017_alter_tasksinfo_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksinfo',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
