# Generated by Django 4.1.4 on 2023-03-10 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UrlSearch', '0018_alter_tasksinfo_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedetails',
            name='PublicId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_college_details', to='UrlSearch.basicinformation'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='PublicId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='UrlSearch.basicinformation'),
        ),
    ]
