# Generated by Django 4.1.4 on 2023-03-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrlSearch', '0020_collegedetails_collegecity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegedetails',
            old_name='CollegeSate',
            new_name='CollegeState',
        ),
    ]
