# Generated by Django 4.1.4 on 2023-03-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlSearch', '0021_rename_collegesate_collegedetails_collegestate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='c_Location',
            new_name='CompanyCity',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='CompanyContinent',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='CompanyCountry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='CompanyState',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
