# Generated by Django 4.1.4 on 2023-01-26 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='designation_list',
            new_name='designation_List',
        ),
    ]
